### PR TITLE
switch from block slots to component helper

### PR DESCRIPTION
**Pull request by srowhani**
#major#

Demo URL: http://ciena-frost.github.io/ember-frost-info-bar/
Old Version: http://srowhani.github.io/ember-frost-info-bar/
# Changelog
- Switched from block-slots to `(component)` helper.

### CODE REVIEW

**Comment by sglanzer** [comment]
Freakin' `actions` are screwing up all our naming - this is approved (nice work), I just want to spend the evening thinking about the naming before we finalize

**Comment by srowhani** [comment]
screen shot 2016-09-12 at 6 19 58 pm

**Comment by sglanzer** [comment]
A couple notes - the `title` should just be text - the `summary` can be either text or a component and right now I'm leaning towards using `buttons` and `links` instead of the `-module` forced on us by `actions` not being available

I think I can justify this, since `links` are always supposed to be located to the right of `buttons`, so we shouldn't need to mix the two sets

**Comment by sglanzer** [comment]
Possibly `controls` instead of actions on a broader basis, which would make the `controls-module` something like `scopeControls`

**Comment by sglanzer** [comment]
Settled on `controls` - so we can make the middle one `scope` or `scopeControls`

**Comment by sglanzer** [comment]
Approved - thanks Seena!

**Pull request merged**
